#!/bin/bash
# ----------------------------------------------------------------------------
# Bundle WebView HTML content into C++ header
#
# This script takes the built React app and creates a header file with the
# HTML content embedded as a C string for use in the PCL module.
# ----------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEBVIEW_DIR="${SCRIPT_DIR}/../../dist"
OUTPUT_FILE="${SCRIPT_DIR}/WebViewContent.h"

# Check if dist directory exists
if [ ! -d "$WEBVIEW_DIR" ]; then
    echo "Error: dist directory not found. Run 'npm run build' first."
    exit 1
fi

# Read HTML file
HTML_FILE="${WEBVIEW_DIR}/index.html"
if [ ! -f "$HTML_FILE" ]; then
    echo "Error: index.html not found in dist/"
    exit 1
fi

# Get CSS and JS filenames
CSS_FILE=$(ls "${WEBVIEW_DIR}/assets/"*.css 2>/dev/null | head -1)
JS_FILE=$(ls "${WEBVIEW_DIR}/assets/"*.js 2>/dev/null | head -1)

if [ -z "$CSS_FILE" ] || [ -z "$JS_FILE" ]; then
    echo "Error: CSS or JS file not found in dist/assets/"
    exit 1
fi

echo "Bundling WebView content..."
echo "  HTML: $HTML_FILE"
echo "  CSS:  $CSS_FILE"
echo "  JS:   $JS_FILE"

# Read file contents
HTML_CONTENT=$(cat "$HTML_FILE")
CSS_CONTENT=$(cat "$CSS_FILE")
JS_CONTENT=$(cat "$JS_FILE")

# Create the inlined HTML with embedded CSS and JS
INLINED_HTML="<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>AstroStretch Studio</title>
    <style>
${CSS_CONTENT}
    </style>
</head>
<body>
    <div id=\"root\"></div>
    <script>
${JS_CONTENT}
    </script>
    <script>
    // Bridge for PCL communication
    window.pclSendMessage = function(msg) {
        if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.cycript) {
            window.webkit.messageHandlers.cycript.postMessage(msg);
        }
    };

    // Listen for messages from PCL
    window.addEventListener('message', function(event) {
        if (event.data && event.data.type) {
            // Handle incoming messages from PCL
            const msg = event.data;

            if (msg.type === 'setImage' && msg.data) {
                // Decode base64 image data
                const binaryString = atob(msg.data);
                const bytes = new Uint8Array(binaryString.length);
                for (let i = 0; i < binaryString.length; i++) {
                    bytes[i] = binaryString.charCodeAt(i);
                }

                // Create ImageData
                const imageData = new ImageData(
                    new Uint8ClampedArray(bytes.buffer),
                    msg.width,
                    msg.height
                );

                // Dispatch custom event for React app
                window.dispatchEvent(new CustomEvent('pclImageData', { detail: imageData }));
            }
            else if (msg.type === 'setParameters') {
                window.dispatchEvent(new CustomEvent('pclParameters', { detail: msg }));
            }
        }
    });
    </script>
</body>
</html>"

# Escape the HTML for C string
escape_for_c() {
    echo "$1" | sed 's/\\/\\\\/g; s/"/\\"/g; s/$/\\n\\/g' | head -c -2
}

# Write header file
cat > "$OUTPUT_FILE" << 'HEADER_START'
// ----------------------------------------------------------------------------
// WebViewContent.h - Auto-generated file
// DO NOT EDIT - This file is generated by bundle-webview.sh
// ----------------------------------------------------------------------------

#ifndef __WebViewContent_h
#define __WebViewContent_h

namespace pcl
{

static const char* WEBVIEW_HTML_CONTENT = R"RAWHTML(
HEADER_START

echo "$INLINED_HTML" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'HEADER_END'
)RAWHTML";

} // namespace pcl

#endif // __WebViewContent_h

// ----------------------------------------------------------------------------
HEADER_END

echo "Generated: $OUTPUT_FILE"
echo "Done!"
